/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSearchRouteImport } from './routes/shop.search'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopAccountRouteImport } from './routes/shop.account'
import { Route as DemoTranslateRouteImport } from './routes/demo/translate'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as ApiTranslateRouteImport } from './routes/api.translate'
import { Route as ShopAccountIndexRouteImport } from './routes/shop.account.index'
import { Route as ShopProductsHandleRouteImport } from './routes/shop.products.$handle'
import { Route as ShopPoliciesHandleRouteImport } from './routes/shop.policies.$handle'
import { Route as ShopPagesHandleRouteImport } from './routes/shop.pages.$handle'
import { Route as ShopCollectionsHandleRouteImport } from './routes/shop.collections.$handle'
import { Route as ShopAccountOrdersRouteImport } from './routes/shop.account.orders'
import { Route as ShopAccountLogoutRouteImport } from './routes/shop.account.logout'
import { Route as ShopAccountLoginRouteImport } from './routes/shop.account.login'
import { Route as ShopAccountCallbackRouteImport } from './routes/shop.account.callback'
import { Route as ShopAccountAddressesRouteImport } from './routes/shop.account.addresses'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as ShopAccountOrdersIdRouteImport } from './routes/shop.account.orders.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const DemoTranslateRoute = DemoTranslateRouteImport.update({
  id: '/demo/translate',
  path: '/demo/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAccountIndexRoute = ShopAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopProductsHandleRoute = ShopProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPoliciesHandleRoute = ShopPoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPagesHandleRoute = ShopPagesHandleRouteImport.update({
  id: '/pages/$handle',
  path: '/pages/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionsHandleRoute = ShopCollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountOrdersRoute = ShopAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountLogoutRoute = ShopAccountLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountLoginRoute = ShopAccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountCallbackRoute = ShopAccountCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountAddressesRoute = ShopAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ShopAccountRoute,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopAccountOrdersIdRoute = ShopAccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopAccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/shop': typeof ShopRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/translate': typeof DemoTranslateRoute
  '/shop/account': typeof ShopAccountRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/callback': typeof ShopAccountCallbackRoute
  '/shop/account/login': typeof ShopAccountLoginRoute
  '/shop/account/logout': typeof ShopAccountLogoutRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
  '/shop/account/': typeof ShopAccountIndexRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/api/translate': typeof ApiTranslateRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/translate': typeof DemoTranslateRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop': typeof ShopIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/callback': typeof ShopAccountCallbackRoute
  '/shop/account/login': typeof ShopAccountLoginRoute
  '/shop/account/logout': typeof ShopAccountLogoutRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
  '/shop/account': typeof ShopAccountIndexRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mcp': typeof McpRoute
  '/shop': typeof ShopRouteWithChildren
  '/api/translate': typeof ApiTranslateRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/translate': typeof DemoTranslateRoute
  '/shop/account': typeof ShopAccountRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/callback': typeof ShopAccountCallbackRoute
  '/shop/account/login': typeof ShopAccountLoginRoute
  '/shop/account/logout': typeof ShopAccountLogoutRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
  '/shop/account/': typeof ShopAccountIndexRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/mcp'
    | '/shop'
    | '/api/translate'
    | '/demo/clerk'
    | '/demo/i18n'
    | '/demo/mcp-todos'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/demo/translate'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/demo/api/mcp-todos'
    | '/demo/sentry/testing'
    | '/shop/account/addresses'
    | '/shop/account/callback'
    | '/shop/account/login'
    | '/shop/account/logout'
    | '/shop/account/orders'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
    | '/shop/account/'
    | '/shop/account/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/mcp'
    | '/api/translate'
    | '/demo/clerk'
    | '/demo/i18n'
    | '/demo/mcp-todos'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/demo/translate'
    | '/shop/cart'
    | '/shop/search'
    | '/shop'
    | '/demo/api/mcp-todos'
    | '/demo/sentry/testing'
    | '/shop/account/addresses'
    | '/shop/account/callback'
    | '/shop/account/login'
    | '/shop/account/logout'
    | '/shop/account/orders'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
    | '/shop/account'
    | '/shop/account/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/mcp'
    | '/shop'
    | '/api/translate'
    | '/demo/clerk'
    | '/demo/i18n'
    | '/demo/mcp-todos'
    | '/demo/prisma'
    | '/demo/tanstack-query'
    | '/demo/translate'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/demo/api/mcp-todos'
    | '/demo/sentry/testing'
    | '/shop/account/addresses'
    | '/shop/account/callback'
    | '/shop/account/login'
    | '/shop/account/logout'
    | '/shop/account/orders'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
    | '/shop/account/'
    | '/shop/account/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  McpRoute: typeof McpRoute
  ShopRoute: typeof ShopRouteWithChildren
  ApiTranslateRoute: typeof ApiTranslateRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTranslateRoute: typeof DemoTranslateRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/demo/translate': {
      id: '/demo/translate'
      path: '/demo/translate'
      fullPath: '/demo/translate'
      preLoaderRoute: typeof DemoTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/account/': {
      id: '/shop/account/'
      path: '/'
      fullPath: '/shop/account/'
      preLoaderRoute: typeof ShopAccountIndexRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/products/$handle': {
      id: '/shop/products/$handle'
      path: '/products/$handle'
      fullPath: '/shop/products/$handle'
      preLoaderRoute: typeof ShopProductsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/policies/$handle': {
      id: '/shop/policies/$handle'
      path: '/policies/$handle'
      fullPath: '/shop/policies/$handle'
      preLoaderRoute: typeof ShopPoliciesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/pages/$handle': {
      id: '/shop/pages/$handle'
      path: '/pages/$handle'
      fullPath: '/shop/pages/$handle'
      preLoaderRoute: typeof ShopPagesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/collections/$handle': {
      id: '/shop/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/shop/collections/$handle'
      preLoaderRoute: typeof ShopCollectionsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account/orders': {
      id: '/shop/account/orders'
      path: '/orders'
      fullPath: '/shop/account/orders'
      preLoaderRoute: typeof ShopAccountOrdersRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/logout': {
      id: '/shop/account/logout'
      path: '/logout'
      fullPath: '/shop/account/logout'
      preLoaderRoute: typeof ShopAccountLogoutRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/login': {
      id: '/shop/account/login'
      path: '/login'
      fullPath: '/shop/account/login'
      preLoaderRoute: typeof ShopAccountLoginRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/callback': {
      id: '/shop/account/callback'
      path: '/callback'
      fullPath: '/shop/account/callback'
      preLoaderRoute: typeof ShopAccountCallbackRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/addresses': {
      id: '/shop/account/addresses'
      path: '/addresses'
      fullPath: '/shop/account/addresses'
      preLoaderRoute: typeof ShopAccountAddressesRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/account/orders/$id': {
      id: '/shop/account/orders/$id'
      path: '/$id'
      fullPath: '/shop/account/orders/$id'
      preLoaderRoute: typeof ShopAccountOrdersIdRouteImport
      parentRoute: typeof ShopAccountOrdersRoute
    }
  }
}

interface ShopAccountOrdersRouteChildren {
  ShopAccountOrdersIdRoute: typeof ShopAccountOrdersIdRoute
}

const ShopAccountOrdersRouteChildren: ShopAccountOrdersRouteChildren = {
  ShopAccountOrdersIdRoute: ShopAccountOrdersIdRoute,
}

const ShopAccountOrdersRouteWithChildren =
  ShopAccountOrdersRoute._addFileChildren(ShopAccountOrdersRouteChildren)

interface ShopAccountRouteChildren {
  ShopAccountAddressesRoute: typeof ShopAccountAddressesRoute
  ShopAccountCallbackRoute: typeof ShopAccountCallbackRoute
  ShopAccountLoginRoute: typeof ShopAccountLoginRoute
  ShopAccountLogoutRoute: typeof ShopAccountLogoutRoute
  ShopAccountOrdersRoute: typeof ShopAccountOrdersRouteWithChildren
  ShopAccountIndexRoute: typeof ShopAccountIndexRoute
}

const ShopAccountRouteChildren: ShopAccountRouteChildren = {
  ShopAccountAddressesRoute: ShopAccountAddressesRoute,
  ShopAccountCallbackRoute: ShopAccountCallbackRoute,
  ShopAccountLoginRoute: ShopAccountLoginRoute,
  ShopAccountLogoutRoute: ShopAccountLogoutRoute,
  ShopAccountOrdersRoute: ShopAccountOrdersRouteWithChildren,
  ShopAccountIndexRoute: ShopAccountIndexRoute,
}

const ShopAccountRouteWithChildren = ShopAccountRoute._addFileChildren(
  ShopAccountRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRouteWithChildren
  ShopCartRoute: typeof ShopCartRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsHandleRoute: typeof ShopCollectionsHandleRoute
  ShopPagesHandleRoute: typeof ShopPagesHandleRoute
  ShopPoliciesHandleRoute: typeof ShopPoliciesHandleRoute
  ShopProductsHandleRoute: typeof ShopProductsHandleRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRouteWithChildren,
  ShopCartRoute: ShopCartRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsHandleRoute: ShopCollectionsHandleRoute,
  ShopPagesHandleRoute: ShopPagesHandleRoute,
  ShopPoliciesHandleRoute: ShopPoliciesHandleRoute,
  ShopProductsHandleRoute: ShopProductsHandleRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  McpRoute: McpRoute,
  ShopRoute: ShopRouteWithChildren,
  ApiTranslateRoute: ApiTranslateRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTranslateRoute: DemoTranslateRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
